export const TITLES_BY_LEVEL: Record<number, { job: string; title: string }> = {
    0: { job: 'Vatandaş', title: 'Hiç Kimse' },
    1: { job: 'Acemi', title: 'Çaylak Avcı' },
    2: { job: 'Gezgin', title: 'Sokak Savaşçısı' },
    3: { job: 'Maceracı', title: 'Yükselen Yıldız' },
    4: { job: 'Savaşçı', title: 'Kurt Katili' },
    5: { job: 'Kıdemli Savaşçı', title: 'Canavar Avcısı' },
    6: { job: 'Gazi', title: 'Zindan Kaşifi' },
    7: { job: 'Elit Savaşçı', title: 'Gölge Takipçisi' },
    8: { job: 'Şövalye', title: 'Sessiz Bıçak' },
    9: { job: 'Kutsal Şövalye', title: 'Işığın Koruyucusu' },
    10: { job: 'Usta', title: 'Element Bükücü' },
    11: { job: 'Büyük Usta', title: 'Rün Büyücüsü' },
    12: { job: 'Lord', title: 'Klan Lideri' },
    13: { job: 'Yüce Lord', title: 'Bölge Komutanı' },
    14: { job: 'İmparator', title: 'Diyar Fatihi' },
    15: { job: 'Yüce İmparator', title: 'Kıta Hükümdarı' },
    16: { job: 'Tiran', title: 'Zalim Hükümdar' },
    17: { job: 'Diktatör', title: 'Mutlak Otorite' },
    18: { job: 'Kaos Elçisi', title: 'Yıkım Getiren' },
    19: { job: 'Kıyamet Habercisi', title: 'Sonun Başlangıcı' },
    20: { job: 'Ejderha Avcısı', title: 'Alevlerin Efendisi' },
    21: { job: 'Ejderha Katili', title: 'Kadimlerin Belası' },
    22: { job: 'Mitolojik Varlık Avcısı', title: 'Efsanelerin Sonu' },
    23: { job: 'Yarı Tanrı', title: 'Ölümlülerin Ötesinde' },
    24: { job: 'Tanrı Katili', title: 'İlahların Düşmanı' },
    25: { job: 'Gölge Hükümdarı', title: 'Tek Gerçek Kral' },
    26: { job: 'Gölge Monarkı', title: 'Ölülerin Efendisi' },
    27: { job: 'Gölge İmparatoru', title: 'Mutlak Varlık' },
    28: { job: 'Kozmik Varlık', title: 'Yıldızların Ötesinde' },
    29: { job: 'Galaktik Hükümdar', title: 'Evrenin Efendisi' },
    30: { job: 'Çoklu Evren Gezgini', title: 'Boyutlar Arası Yolcu' },
    31: { job: 'Paradoks Bekçisi', title: 'Zamanın Koruyucusu' },
    32: { job: 'Gerçeklik Bükücü', title: 'Kaderin Mimarı' },
    33: { job: 'Alfa ve Omega', title: 'Her Şeyin Başı ve Sonu' },
    34: { job: 'Aşkın Varlık', title: 'Varoluşun Üstünde' },
    35: { job: 'Klan Lideri', title: 'Ah-Jin' },
    36: { job: 'Yüce Büyücü', title: 'Kandiaru' },
    37: { job: 'Buz Monarkı', title: 'Beyaz Alevlerin Kralı' },
    38: { job: 'Canavar Monarkı', title: 'Dişlerin Kralı' },
    39: { job: 'Veba Monarkı', title: 'Böceklerin Kraliçesi' },
    40: { job: 'Demir Beden Monarkı', title: 'İnsanların Kralı' },
    41: { job: 'Yıkım Monarkı', title: 'Vahşi Ejderhaların Kralı' },
    42: { job: 'En Parlak Işık Parçası', title: 'Yüce Hükümdar' },
    43: { job: 'Gökyüzü Ordusu', title: '6 Kanatlı Asker' },
    44: { job: 'Mareşal', title: 'Bellion' },
    45: { job: 'Büyük Mareşal', title: 'Yüce Asker' },
    46: { job: 'Ulusal Seviye Avcı', title: '5 Büyük Avcıdan Biri' },
    47: { job: 'Sıralama Başı', title: 'Kore 1.si' },
    48: { job: 'Guild Master', title: 'Avcılar Birliği Başkanı' },
    49: { job: 'S Rank', title: 'Özel Yetkili' },
    50: { job: 'A Rank', title: 'Elit Avcı' },
    51: { job: 'B Rank', title: 'Kıdemli Avcı' },
    52: { job: 'C Rank', title: 'Ortalama Avcı' },
    53: { job: 'D Rank', title: 'Zayıf Avcı' },
    54: { job: 'E Rank', title: 'En Zayıf Avcı' },
    55: { job: 'Uyanmamış', title: 'Potansiyel Sahibi' },
    56: { job: 'Çifte Uyanış', title: 'Nadir Yetenek' },
    57: { job: 'Sistem Oyuncusu', title: 'Tekil Varlık' },
    58: { job: 'Necromancer', title: 'Ölüleri Uyandıran' },
    59: { job: 'Gölge Lordu', title: 'Ordu Komutanı' },
    60: { job: 'İgris', title: 'Kan Kırmızı Komutan' },
    61: { job: 'Tank', title: 'Yıkılmaz Savunma' },
    62: { job: 'Greed', title: 'Açgözlü Gölge' },
    63: 'Beru', title: 'Karınca Kral' },
    64: 'Tusk', title: 'Yüce Şaman' },
    65: 'Jima', title: 'Naga Lideri' },
    66: 'Kaisel', title: 'Ejderha Yoldaş' },
    67: { job: 'Şifacı', title: 'Hayat Veren' },
    68: { job: 'Destek', title: 'Takım Oyuncusu' },
    69: { job: 'Suikastçı', title: 'Sessiz Ölüm' },
    70: { job: 'Büyücü', title: 'Mana Ustası' },
    71: { job: 'Okçu', title: 'Keskin Göz' },
    72: { job: 'Zanaatkar', title: 'Usta Üretici' },
    73: { job: 'Simyacı', title: 'İksir Uzmanı' },
    74: { job: 'Kaşif', title: 'Bilinmeyenin Haritacısı' },
    75: { job: 'Stratejist', title: 'Savaş Taktisyeni' },
    76: { job: 'Diplomat', title: 'Barış Sağlayıcı' },
    77: { job: 'Tüccar', title: 'Altın Efendisi' },
    78: { job: 'Bilgin', title: 'Kayıp Bilginin Koruyucusu' },
    79: { job: 'Gardiyan', title: 'Geçit Bekçisi' },
    80: { job: 'Hayalet', title: 'Görünmez Tehdit' },
    81: { job: 'Fırtına Çağıran', title: 'Doğanın Gazabı' },
    82: { job: 'Zihin Okuyan', title: 'Sırların Fısıltısı' },
    83: { job: 'İllüzyonist', title: 'Gerçeklik Aldatmacası' },
    84: { job: 'Yeminli', title: 'Kırılmaz İrade' },
    85: { job: 'Mirasçı', title: 'Gölgenin Varisi' },
    86: { job: 'Kahin', title: 'Geleceği Gören' },
    87: { job: 'Elementalist', title: 'Dört Elementin Ustası' },
    88: { job: 'Zaman Gezgini', title: 'Geçmişin ve Geleceğin Yolcusu' },
    89: { job: 'Boyut Yırtan', title: 'Evrenler Arası Geçit' },
    90: { job: 'Yıldız Dövücüsü', title: 'Kozmik Silah Ustası' },
    91: { job: 'Hiçlik Lordu', title: 'Boşluğun Efendisi' },
    92: { job: 'Yaratıcı', title: 'Dünyaların Mimarı' },
    93: { job: 'Koruyucu', title: 'Masumların Kalkanı' },
    94: { job: 'Kıyamet', title: 'Dengenin Yıkımı' },
    95: { job: 'Kurtarıcı', title: 'Umudun Işığı' },
    96: { job: 'Miracle', title: 'İmkansızın Gerçekleşmesi' },
    97: { job: 'Efsane', title: 'Zamanın Ötesindeki Hikaye' },
    98: { job: 'Mutlak', title: 'Tartışmasız Güç' },
    99: { job: 'The One', title: 'Her Şeyin Üstündeki' },
    100: { job: 'Oyuncu', title: 'Oyunun Kendisi' },
};

export function getTitleForLevel(level: number): { job: string; title: string } {
    if (level > 100) {
        return TITLES_BY_LEVEL[100];
    }
    return TITLES_BY_LEVEL[level] || TITLES_BY_LEVEL[0];
}
